Feature/add button component
isdi-coders-2023/coding-adventure-Jaume-Cuadrada-front-202301-BCN pull request #1
Opened 2023-02-27 15:55 UTC by jaumecuadrada

2023-02-27 16:11 UTC, catatarelli requested changes

2023-02-27 16:11 UTC, catatarelli commented on src/index.css
> +  color: #fff;
porque los lis tienen este color por defecto?

2023-02-27 16:11 UTC, catatarelli commented on src/components/Button/Button.test.tsx
> +      const buttonContent = "Sign up";
no hace falta repetir esta variable dos veces.

2023-02-27 16:11 UTC, catatarelli commented on src/components/Button/ButtonStyled.tsx
> +
faltan estilos del boton y una media query. Los colores los podemos llevar a variables o un Theme Provider?

2023-02-27 16:11 UTC, catatarelli commented on src/data/types.ts
> +}
las interfaces de las props siempre las ponemos en el mismo archivo que el componente

2023-02-27 16:33 UTC, jaumecuadrada commented on src/data/types.ts
> +}
OK, arreglado.

2023-02-27 16:36 UTC, jaumecuadrada commented on src/components/Button/Button.test.tsx
> +      const buttonContent = "Sign up";
una es el texto que introduzco para el test y el otro el texto esperado, de esa manera puedo romper el test

2023-02-27 16:36 UTC, jaumecuadrada commented on src/index.css
> +  color: #fff;
error, ya lo he modificado

2023-02-28 12:17 UTC, benjaminrae commented
@jaumecuadrada Recuerda que los mensajes de commits deben describir cambios en el codigo, `Button corrections` podria ser mas descriptivo

2023-02-28 12:17 UTC, benjaminrae commented on src/data/types.ts
> +}
@jaumecuadrada Recuerda que deberias marcar las convesaciones como resueltas

2023-02-28 12:21 UTC, benjaminrae requested changes

2023-02-28 12:21 UTC, benjaminrae commented on src/components/Button/Button.test.tsx
> +      const buttonContent = "Sign up";
@jaumecuadrada Pero no utilices el expected en un expect. Y ademas queremos saber aqui que se renderiza un boton con el texto que pasamos al componente Button

2023-02-28 12:21 UTC, benjaminrae commented on src/components/Button/ButtonStyled.tsx
> +  background-color: #cccf18;
Si no quieres usar un ThemeProvider, puedes usar variables de css para el css que repite como colores y fuentes

2023-02-28 12:21 UTC, benjaminrae commented on src/styles/globalStyles.css
> +  --main-color: #cccf18;
Veo que has puesto variables de CSS, deberias usarlos en el componente boton.

2023-02-28 14:42 UTC, jaumecuadrada commented
He cambiado las variables locales y otras correcciones.

2023-02-28 14:45 UTC, bertoforteza approved these changes

2023-02-28 14:45 UTC, bertoforteza commented on src/styles/globalStyles.css
> +  --main-color: #cccf18;
Veo que ya tienes las variables en el componente.

2023-02-28 14:46 UTC, merged